### ISSUE TITLE
Cloning locations returned

### ISSUE THREAD

**Issue by KimBruce** [gracelang/objectdraw#18]
Methods that return a Point describing a component of a geometric object (upper left corner of a geometric object, endpoint of a line) need to return a clone of the Point rather than the instance variable of the object as otherwise translations of the points (outside the object) will affect the objects they are part of.

**Comment by kjx** [comment]
Umm, why are Points mutable?
J

**Comment by KimBruce** [comment]
You are right. They are not mutable. I got confused with a problem we had
with the Java version.

On Saturday, June 6, 2015, kjx <notifications@github.com> wrote:

> Umm, why are Points mutable?
> J
>
> > On 6/06/2015, at 5:32am, Kim Bruce <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > Methods that return a Point describing a component of a geometric object
> (upper left corner of a geometric object, endpoint of a line) need to
> return a clone of the Point rather than the instance variable of the object
> as otherwise translations of the points (outside the object) will affect
> the objects they are part of.
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gracelang/objectdraw/issues/18#issuecomment-109543484>
> .
>


-- 
Prof. Kim Bruce
Computer Science
Pomona College

**Comment by apblack** [comment]
It would be nice is we could annotate objects as being immutable.
