### ISSUE TITLE
Color class

### ISSUE THREAD

**Issue by KimBruce** [gracelang/objectdraw#19]
The defs red, green, and blue in class color (in objectdraw) should all be readable not public.  Actually, for defs readable and public are the same.  Which do we prefer?
(and how do I close an issue that has been opened in error)?

**Comment by kjx** [comment]
> On 8/06/2015, at 17:07pm, Kim Bruce <notifications@github.com> wrote:
> 
> The defs red, green, and blue in class color (in objectdraw) should all be readable not public.

does this make any difference?
in fact: can defs be readable - they can’t be writeable?

J

**Comment by apblack** [comment]
We previously decided that defs should be annotated as ```public``` rather than ```readable```.  Both mean the same thing, but as a result of this I recall doing a mass-edit of my code.

I don't see any reason to change this decision.  Are you proposing one?

**Comment by KimBruce** [comment]
I realized after posting that they were the same.  I'm happy to stick with
what we have.

Is there any way of canceling an issue once it has been posted.  I'm
clearly posting things too late at night!!
